/**
 * Generated by tools/build-art.ts (`npm run art`) from art-source/cats/: do not edit by hand.
 * One entry per look (index 0 is look 1): the sprite in public/assets/cats/, its side and the body
 * circle's radius in sprite pixels (the circle is centred in the sprite) and the body's colour.
 */
import type { CatSprite } from './catSprites';

export const CAT_SPRITE_DATA: readonly CatSprite[] = [
  { file: 'look-01.webp', side: 988, radius: 425.09, color: '#fefefe' },
  { file: 'look-02.webp', side: 976, radius: 425.53, color: '#605454' },
  { file: 'look-03.webp', side: 988, radius: 425.11, color: '#faaf6e' },
  { file: 'look-04.webp', side: 990, radius: 425.02, color: '#70c5ec' },
  { file: 'look-05.webp', side: 1010, radius: 423.02, color: '#fdd1c6' },
  { file: 'look-06.webp', side: 926, radius: 411.45, color: '#b9ca83' },
  { file: 'look-07.webp', side: 988, radius: 424.97, color: '#bb9ac5' },
  { file: 'look-08.webp', side: 922, radius: 389.95, color: '#f57158' },
  { file: 'look-09.webp', side: 988, radius: 425.11, color: '#e0a84b' },
];
