/**
 * Generated by tools/build-art.ts (`npm run art`) from art-source/transition/: do not edit by
 * hand. The growth clouds' sprites in public/assets/transition/ (see cloudSprites.ts).
 */
import type { CloudSprite } from './cloudSprites';

export const CLOUD_SPRITE_DATA: readonly CloudSprite[] = [
  { file: 'cloud-1.webp', width: 363, height: 250 },
  { file: 'cloud-2.webp', width: 366, height: 230 },
  { file: 'cloud-3.webp', width: 361, height: 243 },
  { file: 'cloud-4.webp', width: 313, height: 224 },
  { file: 'cloud-5.webp', width: 320, height: 222 },
  { file: 'cloud-6.webp', width: 316, height: 230 },
  { file: 'cloud-7.webp', width: 288, height: 228 },
  { file: 'cloud-8.webp', width: 310, height: 221 },
  { file: 'cloud-9.webp', width: 307, height: 224 },
];
