/**
 * Generated by tools/build-art.ts (`npm run art`) from art-source/doors/: do not edit by hand.
 * The stage doors' sprites in public/assets/doors/ (see doorSprites.ts for each field).
 */
import type { DoorSprites } from './doorSprites';

export const DOOR_SPRITE_DATA: DoorSprites = {
  picture: {
    file: 'picture.webp',
    width: 768,
    height: 1376,
  },
  panel: {
    file: 'panel.webp',
    width: 652,
    height: 1230,
    top: 300,
    right: 72,
    bottom: 299,
    left: 72,
  },
};
