/**
 * Generated by tools/build-art.ts (`npm run art`) from art-source/hud/: do not edit by hand.
 * The HUD sprites in public/assets/hud/ (see hudSprites.ts for each field).
 */
import type { HudBubbleSprite, HudCardSprite, HudSprite } from './hudSprites';

export const HUD_COINS_SPRITE: HudCardSprite = {
  file: 'coins.webp',
  width: 1156,
  height: 346,
  textLeft: 0.28,
  textRight: 0.93,
  iconX: 0.13,
  iconY: 0.5,
};
export const HUD_SCORE_SPRITE: HudCardSprite = {
  file: 'score.webp',
  width: 1156,
  height: 346,
  textLeft: 0.28,
  textRight: 0.93,
  iconX: 0.13,
  iconY: 0.5,
};
export const HUD_NEXT_SPRITE: HudBubbleSprite = {
  file: 'next.webp',
  width: 823,
  height: 877,
  cx: 0.5,
  cy: 0.53,
  r: 0.5,
  tagY: 0.08,
};
export const HUD_PAUSE_SPRITE: HudSprite = { file: 'pause.webp', width: 746, height: 746 };
