/**
 * Generated by tools/build-art.ts (`npm run art`) from art-source/hud/: do not edit by hand.
 * The HUD sprites in public/assets/hud/ (see hudSprites.ts for each field).
 */
import type { HudBubbleSprite, HudSprite } from './hudSprites';

export const HUD_COIN_SPRITE: HudSprite = { file: 'coin.webp', width: 230, height: 230 };
export const HUD_BADGE_SPRITE: HudSprite = { file: 'paw-badge.webp', width: 294, height: 294 };
export const HUD_NEXT_SPRITE: HudBubbleSprite = {
  file: 'next.webp',
  width: 823,
  height: 877,
  cx: 0.5,
  cy: 0.53,
  r: 0.5,
  tagY: 0.08,
};
export const HUD_PAUSE_SPRITE: HudSprite = { file: 'pause.webp', width: 746, height: 746 };
