/**
 * Generated by tools/build-art.ts (`npm run art`) from art-source/icons/ and the upgrade icon
 * sheet: do not edit by hand. The icon kit's sprites in public/assets/icons/ (see iconSprites.ts).
 */
import type { CatSprite } from './catSprites';

export const ICON_SPRITE_DATA: Readonly<Record<string, CatSprite>> = {
  bigCatch: {
    file: 'bigCatch.webp',
    side: 912,
    radius: 436.31,
    color: '#edd9a7',
  },
  comboCharm: {
    file: 'comboCharm.webp',
    side: 476,
    radius: 227.24,
    color: '#f0d9ac',
  },
  luckyPaw: {
    file: 'luckyPaw.webp',
    side: 460,
    radius: 223.06,
    color: '#eedaac',
  },
  secondChance: {
    file: 'secondChance.webp',
    side: 774,
    radius: 383.7,
    color: '#f6db8a',
  },
};
