/**
 * Generated by tools/build-art.ts (`npm run art`) from art-source/menu/: do not edit by hand.
 * The main menu's sprites in public/assets/menu/ (see menuSprites.ts for each field).
 */
import type { MenuSprites } from './menuSprites';

export const MENU_SPRITE_DATA: MenuSprites = {
  background: { file: 'background.webp', width: 768, height: 1376, sky: '#f3ebc7' },
  logo: { file: 'logo.webp', width: 921, height: 482 },
  hero: { file: 'hero.webp', width: 742, height: 648 },
  gear: { file: 'gear.webp', width: 168, height: 176 },
  play: { file: 'play.webp', width: 242, height: 194, cap: 117 },
  upgrades: { file: 'upgrades.webp', width: 198, height: 158, cap: 95 },
  coinsPill: { file: 'coins-pill.webp', width: 218, height: 175, cap: 105 },
  card: { file: 'card.webp', width: 964, height: 651, slice: 109 },
  well: { file: 'well.webp', width: 262, height: 211, cap: 127 },
  coin: { file: 'coin.webp', width: 214, height: 225 },
  torii: { file: 'torii.webp', width: 273, height: 234 },
  arrow: { file: 'arrow.webp', width: 144, height: 160 },
  sparkle: { file: 'sparkle.webp', width: 151, height: 172 },
  sparkleSmall: { file: 'sparkle-small.webp', width: 99, height: 109 },
};
