/**
 * Generated by tools/build-art.ts (`npm run art`) from art-source/picks/: do not edit by hand.
 * The pick cards' pictures in public/assets/picks/ (see pickSprites.ts).
 */
import type { PickPicture } from './pickSprites';

export const PICK_SPRITE_DATA: Readonly<Record<string, PickPicture>> = {
  moreBoulders: {
    file: 'moreBoulders.webp',
    width: 910,
    height: 904,
  },
};
