/**
 * Generated by tools/build-art.ts (`npm run art`) from art-source/picks/: do not edit by hand.
 * The pick cards' pictures in public/assets/picks/ (see pickSprites.ts).
 */
import type { PickPicture } from './pickSprites';

export const PICK_SPRITE_DATA: Readonly<Record<string, PickPicture>> = {
  bigBoulders: {
    file: 'bigBoulders.webp',
    width: 1012,
    height: 1008,
  },
  moreBoulders: {
    file: 'moreBoulders.webp',
    width: 909,
    height: 815,
  },
};
