/**
 * Generated by tools/build-art.ts (`npm run art`) from art-source/scene/: do not edit by hand.
 * Image pixels of the sprites in public/assets/scene/ (see sceneSprites.ts for each field).
 */
import type { BackgroundSprite, JarSprite, PawSprite } from './sceneSprites';

export const JAR_SPRITE: JarSprite = {
  back: 'jar-back.webp',
  front: 'jar-front.webp',
  width: 896,
  height: 1200,
  left: 169.5,
  right: 725.5,
  rim: 227.5,
  floor: 1043.5,
  cornerRadius: 156,
  backPieces: [
    { x: 168, y: 80, w: 12, h: 80 },
    { x: 716, y: 80, w: 11, h: 80 },
    { x: 168, y: 160, w: 559, h: 80 },
    { x: 168, y: 240, w: 44, h: 640 },
    { x: 684, y: 240, w: 43, h: 640 },
    { x: 168, y: 880, w: 53, h: 40 },
    { x: 675, y: 880, w: 52, h: 40 },
    { x: 172, y: 920, w: 79, h: 40 },
    { x: 645, y: 920, w: 78, h: 40 },
    { x: 187, y: 960, w: 521, h: 40 },
    { x: 217, y: 1000, w: 461, h: 40 },
    { x: 294, y: 1040, w: 307, h: 40 },
  ],
  frontPieces: [
    { x: 103, y: 80, w: 67, h: 80 },
    { x: 725, y: 80, w: 68, h: 80 },
    { x: 69, y: 160, w: 101, h: 80 },
    { x: 725, y: 160, w: 102, h: 80 },
    { x: 105, y: 240, w: 65, h: 40 },
    { x: 721, y: 240, w: 70, h: 680 },
    { x: 107, y: 280, w: 67, h: 640 },
    { x: 113, y: 920, w: 75, h: 40 },
    { x: 707, y: 920, w: 77, h: 40 },
    { x: 119, y: 960, w: 99, h: 40 },
    { x: 677, y: 960, w: 100, h: 40 },
    { x: 137, y: 1000, w: 154, h: 40 },
    { x: 604, y: 1000, w: 156, h: 40 },
    { x: 167, y: 1040, w: 562, h: 40 },
    { x: 174, y: 1080, w: 548, h: 40 },
    { x: 175, y: 1120, w: 77, h: 40 },
    { x: 644, y: 1120, w: 77, h: 40 },
  ],
};

export const PAW_SPRITE: PawSprite = {
  file: 'paw.webp',
  width: 322,
  height: 1030,
  cx: 161,
  bottom: 1028,
  pawWidth: 316,
  armRow: 4,
};

export const BACKGROUND_SPRITE: BackgroundSprite = {
  file: 'background.webp',
  width: 768,
  height: 1376,
  sky: '#f7f0d4',
  ground: '#ebbb8a',
};
