/**
 * Generated by tools/build-art.ts (`npm run art`) from art-source/scene/: do not edit by hand.
 * Image pixels of the sprites in public/assets/scene/ (see sceneSprites.ts for each field).
 */
import type { BackgroundSprite, JarSprite, NorenSprite, PawSprite } from './sceneSprites';

export const JAR_SPRITE: JarSprite = {
  back: 'jar-back.webp',
  front: 'jar-front.webp',
  width: 896,
  height: 1200,
  left: 178.5,
  right: 718.5,
  rim: 219.5,
  railTop: 167,
  floor: 1034.5,
  backPieces: [
    { x: 177, y: 80, w: 16, h: 80 },
    { x: 705, y: 80, w: 15, h: 80 },
    { x: 177, y: 160, w: 543, h: 120 },
    { x: 177, y: 280, w: 43, h: 680 },
    { x: 677, y: 280, w: 43, h: 680 },
    { x: 177, y: 960, w: 543, h: 80 },
  ],
  frontPieces: [
    { x: 108, y: 80, w: 71, h: 80 },
    { x: 718, y: 80, w: 71, h: 80 },
    { x: 76, y: 160, w: 103, h: 80 },
    { x: 718, y: 160, w: 103, h: 80 },
    { x: 113, y: 240, w: 66, h: 40 },
    { x: 718, y: 240, w: 67, h: 760 },
    { x: 115, y: 280, w: 64, h: 240 },
    { x: 120, y: 520, w: 59, h: 80 },
    { x: 115, y: 600, w: 64, h: 120 },
    { x: 115, y: 720, w: 64, h: 200 },
    { x: 117, y: 920, w: 62, h: 80 },
    { x: 113, y: 1000, w: 672, h: 80 },
    { x: 129, y: 1080, w: 640, h: 40 },
    { x: 183, y: 1120, w: 82, h: 40 },
    { x: 634, y: 1120, w: 81, h: 40 },
  ],
};

export const PAW_SPRITE: PawSprite = {
  file: 'paw.webp',
  width: 322,
  height: 1030,
  cx: 161,
  bottom: 1028,
  pawWidth: 316,
  armRow: 4,
};

export const BACKGROUND_SPRITE: BackgroundSprite = {
  file: 'background.webp',
  width: 768,
  height: 1376,
  sky: '#f7f0d4',
  ground: '#ebbb8a',
};

export const NOREN_SPRITE: NorenSprite = {
  file: 'noren.webp',
  width: 1168,
  height: 750,
  left: 51,
  right: 1118,
  hem: 750,
  sliceTop: 282,
  sliceBottom: 633,
};
