/**
 * Generated by tools/build-art.ts (`npm run art`) from art-source/scene/: do not edit by hand.
 * Image pixels of the sprites in public/assets/scene/ (see sceneSprites.ts for each field).
 */
import type { BackgroundSprite, JarSprite, NorenSprite, PawSprite } from './sceneSprites';

export const JAR_SPRITE: JarSprite = {
  back: 'jar-back.webp',
  front: 'jar-front.webp',
  width: 896,
  height: 1200,
  left: 171.5,
  right: 725.5,
  rim: 227.5,
  railTop: 175,
  floor: 1043.5,
  backPieces: [
    { x: 170, y: 80, w: 10, h: 80 },
    { x: 716, y: 80, w: 11, h: 80 },
    { x: 170, y: 160, w: 557, h: 80 },
    { x: 170, y: 240, w: 49, h: 720 },
    { x: 683, y: 240, w: 44, h: 680 },
    { x: 677, y: 920, w: 50, h: 40 },
    { x: 170, y: 960, w: 557, h: 120 },
  ],
  frontPieces: [
    { x: 103, y: 80, w: 69, h: 80 },
    { x: 725, y: 80, w: 68, h: 80 },
    { x: 69, y: 160, w: 103, h: 80 },
    { x: 725, y: 160, w: 102, h: 80 },
    { x: 105, y: 240, w: 67, h: 40 },
    { x: 725, y: 240, w: 66, h: 720 },
    { x: 107, y: 280, w: 65, h: 680 },
    { x: 114, y: 960, w: 58, h: 40 },
    { x: 725, y: 960, w: 57, h: 80 },
    { x: 122, y: 1000, w: 50, h: 40 },
    { x: 130, y: 1040, w: 636, h: 40 },
    { x: 174, y: 1080, w: 548, h: 40 },
    { x: 175, y: 1120, w: 77, h: 40 },
    { x: 644, y: 1120, w: 77, h: 40 },
  ],
};

export const PAW_SPRITE: PawSprite = {
  file: 'paw.webp',
  width: 322,
  height: 1030,
  cx: 161,
  bottom: 1028,
  pawWidth: 316,
  armRow: 4,
};

export const BACKGROUND_SPRITE: BackgroundSprite = {
  file: 'background.webp',
  width: 768,
  height: 1376,
  sky: '#f7f0d4',
  ground: '#ebbb8a',
};

export const NOREN_SPRITE: NorenSprite = {
  file: 'noren.webp',
  width: 1168,
  height: 750,
  left: 51,
  right: 1118,
  hem: 750,
  sliceTop: 282,
  sliceBottom: 633,
};
