/**
 * Generated by tools/build-art.ts (`npm run art`) from art-source/ui/upgrade-pieces: do not edit
 * by hand. The Upgrades screen's sprites in public/assets/shop/ (see shopSprites.ts).
 */
import type { ShopSprites } from './shopSprites';

export const SHOP_SPRITE_DATA: ShopSprites = {
  card: {
    file: 'card.webp',
    width: 610,
    height: 227,
    corner: 26,
    bottom: 57,
  },
  buy: {
    file: 'buy.webp',
    width: 126,
    height: 97,
    cap: 59,
  },
  title: {
    file: 'title.webp',
    width: 144,
    height: 112,
    cap: 68,
  },
  close: {
    file: 'close.webp',
    width: 111,
    height: 111,
  },
};
