/**
 * Generated by tools/build-art.ts (`npm run art`) from art-source/specials/: do not edit by hand.
 * The special balls' sprites in public/assets/specials/ (see specialSprites.ts for each field).
 */
import type { SpecialSprites } from './specialSprites';

export const SPECIAL_SPRITE_DATA: SpecialSprites = {
  magnet: {
    file: 'magnet.webp',
    side: 798,
    radius: 395.68,
    color: '#ecd3ab',
  },
  hanabi: {
    file: 'hanabi.webp',
    side: 932,
    radius: 366.21,
    color: '#2e3561',
  },
  joker: {
    file: 'joker.webp',
    side: 1126,
    radius: 382.78,
    color: '#cba5f0',
  },
  boulders: [
    {
      file: 'boulder-0.webp',
      side: 432,
      radius: 212.01,
      color: '#a5b1bd',
    },
    {
      file: 'boulder-1.webp',
      side: 448,
      radius: 212.54,
      color: '#7f8d9a',
    },
    {
      file: 'boulder-2.webp',
      side: 440,
      radius: 216.2,
      color: '#656e77',
    },
    {
      file: 'boulder-3.webp',
      side: 446,
      radius: 218.32,
      color: '#636d76',
    },
  ],
};
