/**
 * The icon kit part of the art pipeline (docs/ART_ASSETS.md §5): every round medallion icon, written
 * to `public/assets/icons/<id>.webp` with its measurements in `src/config/iconSpriteData.ts`.
 *
 * - `art-source/icons/<id>.{png,jpg,jpeg,webp}`: one icon per file, named by the id the code uses.
 * - `art-source/ui/upgrade-icons.*`: the first sheet, a 2×2 grid of the upgrades' icons (§4.9). A
 *   quarter is used only when no single file has its id.
 * Each medallion goes through tools/artBall.ts like a ball: its circle is fitted and the sprite is
 * a square centred on it.
 */
import { readdir, mkdir, writeFile } from 'node:fs/promises';
import { join, parse } from 'node:path';
import { buildBall } from './artBall.ts';
import type { BallSprite } from './artBall.ts';
import { crop, findSource, loadRgba } from './artImage.ts';

const SOURCE_DIR = 'art-source/icons';
const SHEET_DIR = 'art-source/ui';
const OUT_DIR = 'public/assets/icons';
const DATA_FILE = 'src/config/iconSpriteData.ts';
/** The upgrade icon sheet's quarters: top left, top right, bottom left, bottom right. */
const SHEET_IDS = ['luckyPaw', 'bigCatch', 'comboCharm', 'secondChance'] as const;

export async function buildIcons(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });
  const icons: Record<string, BallSprite> = {};
  const files = (await readdir(SOURCE_DIR)).filter((f) => /\.(png|jpe?g|webp)$/i.test(f)).sort();
  for (const file of files) {
    const id = parse(file).name;
    icons[id] = await buildBall(join(SOURCE_DIR, file), OUT_DIR, `${id}.webp`);
  }

  const sheet = await loadRgba(await findSource(SHEET_DIR, 'upgrade-icons'));
  const w = Math.floor(sheet.width / 2);
  const h = Math.floor(sheet.height / 2);
  for (const [i, id] of SHEET_IDS.entries()) {
    if (icons[id]) continue;
    const quarter = crop(sheet, { x: (i % 2) * w, y: Math.floor(i / 2) * h, w, h });
    icons[id] = await buildBall(quarter, OUT_DIR, `${id}.webp`);
  }

  await writeFile(DATA_FILE, dataModule(icons));
  console.log(`Icons: ${Object.keys(icons).sort().join(', ')}; wrote ${DATA_FILE}`);
}

function dataModule(icons: Record<string, BallSprite>): string {
  const sorted = Object.fromEntries(Object.entries(icons).sort(([a], [b]) => a.localeCompare(b)));
  return `/**
 * Generated by tools/build-art.ts (\`npm run art\`) from art-source/icons/ and the upgrade icon
 * sheet: do not edit by hand. The icon kit's sprites in public/assets/icons/ (see iconSprites.ts).
 */
import type { CatSprite } from './catSprites';

export const ICON_SPRITE_DATA: Readonly<Record<string, CatSprite>> = ${JSON.stringify(sorted, null, 2)};
`;
}
