/**
 * The growth clouds part of the art pipeline (TECH_SPEC §14, docs/ART_ASSETS.md phase 10): the
 * cloud sheet from `art-source/transition/clouds`, cut into one sprite per cloud in
 * `public/assets/transition/`, with their sizes in `src/config/cloudSpriteData.ts`.
 *
 * The white is cut, and every piece big enough to be a cloud becomes a sprite, in reading order
 * (top row first, left to right).
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { components, cutBackground, findSource, isolate, loadRgba, saveWebp } from './artImage.ts';

const SOURCE_DIR = 'art-source/transition';
const OUT_DIR = 'public/assets/transition';
const DATA_FILE = 'src/config/cloudSpriteData.ts';
/** A piece counts as a cloud when it covers at least this share of the biggest one. */
const MIN_AREA_SHARE = 0.25;
/** Pieces whose tops are this close (px) sit in the same row. */
const ROW_TOLERANCE = 60;
/** Transparent margin kept around each cloud, px. */
const MARGIN = 2;

interface CloudData {
  file: string;
  width: number;
  height: number;
}

export async function buildClouds(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });
  const sheet = await loadRgba(await findSource(SOURCE_DIR, 'clouds'));
  cutBackground(sheet);
  const found = components(sheet);
  const biggest = found[0]?.area ?? 0;
  const pieces = found
    .filter((c) => c.area >= MIN_AREA_SHARE * biggest)
    .sort((a, b) => (Math.abs(a.y - b.y) <= ROW_TOLERANCE ? a.x - b.x : a.y - b.y));
  const clouds: CloudData[] = [];
  for (const [i, piece] of pieces.entries()) {
    const image = isolate(sheet, piece, MARGIN);
    const file = `cloud-${i + 1}.webp`;
    await saveWebp(image, join(OUT_DIR, file));
    clouds.push({ file, width: image.width, height: image.height });
  }
  await writeFile(DATA_FILE, dataModule(clouds));
  console.log(`Clouds: ${clouds.length}; wrote ${DATA_FILE}`);
}

function dataModule(clouds: readonly CloudData[]): string {
  const rows = clouds
    .map((c) => `  { file: '${c.file}', width: ${c.width}, height: ${c.height} },`)
    .join('\n');
  return `/**
 * Generated by tools/build-art.ts (\`npm run art\`) from art-source/transition/: do not edit by
 * hand. The growth clouds' sprites in public/assets/transition/ (see cloudSprites.ts).
 */
import type { CloudSprite } from './cloudSprites';

export const CLOUD_SPRITE_DATA: readonly CloudSprite[] = [
${rows}
];
`;
}
