/**
 * The stage doors part of the art pipeline (TECH_SPEC §14, docs/ART_ASSETS.md phase 6): the picture
 * and the empty door frame from `art-source/doors/`, written to `public/assets/doors/` with their
 * measurements in `src/config/doorSpriteData.ts`.
 *
 * - Picture: converted as is. The game cuts it into four strips, one per door.
 * - Panel: the white outside and the white opening in its middle become transparent, the frame is
 *   cropped, and the opening's edges are measured: the frame becomes a nine-slice whose sides
 *   (the two stiles) stretch to the screen's height while the lattice caps at the top and bottom
 *   stay whole.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import {
  alphaAt,
  crop,
  cutBackground,
  findSource,
  loadRgba,
  opaqueBox,
  saveWebp,
} from './artImage.ts';
import type { Rgba } from './artImage.ts';

const SOURCE_DIR = 'art-source/doors';
const OUT_DIR = 'public/assets/doors';
const DATA_FILE = 'src/config/doorSpriteData.ts';

interface DoorData {
  picture: { file: string; width: number; height: number };
  panel: {
    file: string;
    width: number;
    height: number;
    top: number;
    right: number;
    bottom: number;
    left: number;
  };
}

export async function buildDoors(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });

  const picture = await loadRgba(await findSource(SOURCE_DIR, 'picture'));
  await saveWebp(picture, join(OUT_DIR, 'picture.webp'), 85);

  const raw = await loadRgba(await findSource(SOURCE_DIR, 'panel'));
  const centre = Math.floor(raw.height / 2) * raw.width + Math.floor(raw.width / 2);
  cutBackground(raw, undefined, [centre]);
  const panel = crop(raw, opaqueBox(raw));
  await saveWebp(panel, join(OUT_DIR, 'panel.webp'));
  const opening = measureOpening(panel);

  const data: DoorData = {
    picture: { file: 'picture.webp', width: picture.width, height: picture.height },
    panel: { file: 'panel.webp', width: panel.width, height: panel.height, ...opening },
  };
  await writeFile(DATA_FILE, dataModule(data));
  console.log(
    `Doors: picture ${picture.width}×${picture.height}, panel ${panel.width}×${panel.height}, ` +
      `opening inset ${opening.top}/${opening.right}/${opening.bottom}/${opening.left}; wrote ${DATA_FILE}`,
  );
}

/** How far the opening lies inside each edge, along the middle row and column. */
function measureOpening(image: Rgba): { top: number; right: number; bottom: number; left: number } {
  const { width, height } = image;
  const midX = Math.floor(width / 2);
  const midY = Math.floor(height / 2);
  const clear = (x: number, y: number): boolean => alphaAt(image, x, y) === 0;
  if (!clear(midX, midY)) throw new Error('The panel has no clear opening in its middle');
  let left = midX;
  while (left > 0 && clear(left - 1, midY)) left--;
  let right = midX;
  while (right < width - 1 && clear(right + 1, midY)) right++;
  let top = midY;
  while (top > 0 && clear(midX, top - 1)) top--;
  let bottom = midY;
  while (bottom < height - 1 && clear(midX, bottom + 1)) bottom++;
  return { top, right: width - 1 - right, bottom: height - 1 - bottom, left };
}

function dataModule(data: DoorData): string {
  return `/**
 * Generated by tools/build-art.ts (\`npm run art\`) from art-source/doors/: do not edit by hand.
 * The stage doors' sprites in public/assets/doors/ (see doorSprites.ts for each field).
 */
import type { DoorSprites } from './doorSprites';

export const DOOR_SPRITE_DATA: DoorSprites = ${JSON.stringify(data, null, 2)};
`;
}
