/**
 * Final art pipeline (TECH_SPEC §14, docs/ART_ASSETS.md): turns the owner's generated images into
 * game sprites. Run it with `npm run art` after adding or replacing a file in `art-source/`. The
 * scene (jar, paw, background) is built by tools/buildScene.ts, the HUD by tools/buildHud.ts,
 * the main menu by tools/buildMenu.ts, the stage doors by tools/buildDoors.ts, the special balls by
 * tools/buildSpecials.ts, the Upgrades screen by tools/buildShop.ts and the icon kit by
 * tools/buildIcons.ts, the pick cards' pictures by tools/buildPicks.ts. Cats, special balls and icons
 * go through tools/artBall.ts.
 *
 * For each `art-source/cats/size-NN.{png,jpg,jpeg,webp}` (NN = 01–09, one per look):
 *   1. removes the plain white background: the near-white region connected to the image border,
 *      with the anti-aliased edge un-blended from white, so no white fringe shows on dark ground;
 *   2. fits the body circle to the outline below the ears (the physics circle);
 *   3. crops a square centred on that circle, wide enough for the ears;
 *   4. writes `public/assets/cats/look-NN.webp` and measures the body's colour.
 * The measurements go to `src/config/catSpriteData.ts`, which the game reads.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { buildBall } from './artBall.ts';
import { findSource } from './artImage.ts';
import { buildDoors } from './buildDoors.ts';
import { buildHud } from './buildHud.ts';
import { buildIcons } from './buildIcons.ts';
import { buildMenu } from './buildMenu.ts';
import { buildPicks } from './buildPicks.ts';
import { buildScene } from './buildScene.ts';
import { buildShop } from './buildShop.ts';
import { buildSpecials } from './buildSpecials.ts';

const SOURCE_DIR = 'art-source/cats';
const OUT_DIR = 'public/assets/cats';
const DATA_FILE = 'src/config/catSpriteData.ts';
const LOOK_COUNT = 9;

interface LookData {
  readonly look: number;
  readonly file: string;
  readonly side: number;
  readonly radius: number;
  readonly color: string;
}

async function main(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });
  const looks: LookData[] = [];
  for (let look = 1; look <= LOOK_COUNT; look++) {
    const nn = String(look).padStart(2, '0');
    const source = await findSource(SOURCE_DIR, `size-${nn}`);
    looks.push({ look, ...(await buildBall(source, OUT_DIR, `look-${nn}.webp`)) });
  }
  await writeFile(DATA_FILE, dataModule(looks));
  console.log(`Wrote ${looks.length} cats to ${OUT_DIR} and ${DATA_FILE}`);
  await buildScene();
  await buildHud();
  await buildMenu();
  await buildDoors();
  await buildSpecials();
  await buildShop();
  await buildIcons();
  await buildPicks();
}

function dataModule(looks: readonly LookData[]): string {
  const rows = looks
    .map(
      (l) => `  { file: '${l.file}', side: ${l.side}, radius: ${l.radius}, color: '${l.color}' },`,
    )
    .join('\n');
  return `/**
 * Generated by tools/build-art.ts (\`npm run art\`) from art-source/cats/: do not edit by hand.
 * One entry per look (index 0 is look 1): the sprite in public/assets/cats/, its side and the body
 * circle's radius in sprite pixels (the circle is centred in the sprite) and the body's colour.
 */
import type { CatSprite } from './catSprites';

export const CAT_SPRITE_DATA: readonly CatSprite[] = [
${rows}
];
`;
}

await main();
