/**
 * The pick cards' pictures (docs/ART_ASSETS.md §4.9): drawings that are not a single ball, like the
 * heap of boulders for More Boulders, from `art-source/picks/<id>.*`, written to
 * `public/assets/picks/<id>.webp` with their sizes in `src/config/pickSpriteData.ts`. The white is
 * cut and the picture is cropped to what is drawn; the game fits it in the card's medallion.
 */
import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { join, parse } from 'node:path';
import { crop, cutBackground, loadRgba, opaqueBox, saveWebp } from './artImage.ts';

const SOURCE_DIR = 'art-source/picks';
const OUT_DIR = 'public/assets/picks';
const DATA_FILE = 'src/config/pickSpriteData.ts';
/** Transparent margin around a picture, px. */
const MARGIN = 2;

interface Picture {
  file: string;
  width: number;
  height: number;
}

export async function buildPicks(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });
  const pictures: Record<string, Picture> = {};
  const files = (await readdir(SOURCE_DIR)).filter((f) => /\.(png|jpe?g|webp)$/i.test(f)).sort();
  for (const file of files) {
    const id = parse(file).name;
    const image = await loadRgba(join(SOURCE_DIR, file));
    cutBackground(image);
    const box = opaqueBox(image);
    const picture = crop(image, {
      x: box.x - MARGIN,
      y: box.y - MARGIN,
      w: box.w + 2 * MARGIN,
      h: box.h + 2 * MARGIN,
    });
    await saveWebp(picture, join(OUT_DIR, `${id}.webp`));
    pictures[id] = { file: `${id}.webp`, width: picture.width, height: picture.height };
  }
  await writeFile(DATA_FILE, dataModule(pictures));
  console.log(`Pick pictures: ${Object.keys(pictures).join(', ') || 'none'}; wrote ${DATA_FILE}`);
}

function dataModule(pictures: Record<string, Picture>): string {
  return `/**
 * Generated by tools/build-art.ts (\`npm run art\`) from art-source/picks/: do not edit by hand.
 * The pick cards' pictures in public/assets/picks/ (see pickSprites.ts).
 */
import type { PickPicture } from './pickSprites';

export const PICK_SPRITE_DATA: Readonly<Record<string, PickPicture>> = ${JSON.stringify(pictures, null, 2)};
`;
}
