/**
 * The special balls part of the art pipeline (TECH_SPEC §14, docs/ART_ASSETS.md phase 7): the
 * magnet, the hanabi, the joker cat and the boulder sheet from `art-source/specials/`, written to
 * `public/assets/specials/` with their measurements in `src/config/specialSpriteData.ts`.
 *
 * Each ball goes through tools/artBall.ts like a cat. The boulder sheet is a 2×2 grid of the same
 * stone with 0, 1, 2 and 3 iron bands; it is cut into its four quarters first.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { buildBall } from './artBall.ts';
import type { BallSprite } from './artBall.ts';
import { crop, findSource, loadRgba } from './artImage.ts';

const SOURCE_DIR = 'art-source/specials';
const OUT_DIR = 'public/assets/specials';
const DATA_FILE = 'src/config/specialSpriteData.ts';

interface SpecialData {
  magnet: BallSprite;
  hanabi: BallSprite;
  joker: BallSprite;
  boulders: BallSprite[];
}

export async function buildSpecials(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });
  const source = (base: string): Promise<string> => findSource(SOURCE_DIR, base);
  const magnet = await buildBall(await source('magnet'), OUT_DIR, 'magnet.webp');
  const hanabi = await buildBall(await source('hanabi'), OUT_DIR, 'hanabi.webp');
  const joker = await buildBall(await source('joker'), OUT_DIR, 'joker.webp');

  // Top left, top right, bottom left, bottom right: 0, 1, 2 and 3 bands.
  const sheet = await loadRgba(await source('boulders'));
  const w = Math.floor(sheet.width / 2);
  const h = Math.floor(sheet.height / 2);
  const boulders: BallSprite[] = [];
  for (let bands = 0; bands < 4; bands++) {
    const quarter = crop(sheet, { x: (bands % 2) * w, y: Math.floor(bands / 2) * h, w, h });
    boulders.push(await buildBall(quarter, OUT_DIR, `boulder-${bands}.webp`));
  }

  await writeFile(DATA_FILE, dataModule({ magnet, hanabi, joker, boulders }));
  console.log(
    `Specials: magnet, hanabi, joker and ${boulders.length} boulders; wrote ${DATA_FILE}`,
  );
}

function dataModule(data: SpecialData): string {
  return `/**
 * Generated by tools/build-art.ts (\`npm run art\`) from art-source/specials/: do not edit by hand.
 * The special balls' sprites in public/assets/specials/ (see specialSprites.ts for each field).
 */
import type { SpecialSprites } from './specialSprites';

export const SPECIAL_SPRITE_DATA: SpecialSprites = ${JSON.stringify(data, null, 2)};
`;
}
